[package]
name = "aero-live-srt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
aero-common.workspace = true
aero-live-core.workspace = true
aero-storage.workspace = true

tokio = { workspace = true, features = ["net", "io-util", "rt", "sync", "macros"] }
async-trait.workspace = true
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
ulid = { workspace = true, features = ["serde", "uuid"] }
