[package]
name = "aero-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "aero-eng"
path = "src/main.rs"

[dependencies]
aero-eng.workspace = true
tokio.workspace = true
serde_json.workspace = true
async-trait.workspace = true
