[package]
name = "aero-live-hls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
aero-common.workspace = true
aero-live-core.workspace = true

tokio = { workspace = true, features = ["fs", "io-util", "sync"] }
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
time.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "fs", "io-util", "sync"] }
tempfile = "3"
pretty_assertions.workspace = true
