[package]
name = "aero-live-rtmp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
aero-common.workspace = true
aero-storage.workspace = true
aero-live-core.workspace = true
aero-live-hls.workspace = true

tokio = { workspace = true, features = ["net", "io-util", "rt", "macros", "sync", "time"] }
async-trait.workspace = true
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true

rml_rtmp = "0.8"
ulid = { workspace = true, features = ["serde", "uuid"] }
