[package]
name = "aero-bus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
aero-common.workspace = true

tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
async-trait.workspace = true
async-nats.workspace = true

serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
bytes.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
