[package]
name = "aero-live-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
aero-common.workspace = true
aero-storage.workspace = true

async-trait.workspace = true
sqlx.workspace = true

serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
ulid = { workspace = true, features = ["serde", "uuid"] }
