//! HTTP/WS gateway. Composes auth + im-core + bus + storage into Axum routes.

pub mod agent_bot;
pub mod moderation_bot;
pub mod transcribe_bot;
pub mod unfurl_bot;
pub mod ai_adapter;
pub mod bookmarks;
pub mod channel_sections;
pub mod collab;
pub mod config;
pub mod drafts;
pub mod emoji;
pub mod error;
pub mod guests;
pub mod hub;
pub mod invitations;
pub mod live;
pub mod metrics;
pub mod notif_prefs;
pub mod pat;
pub mod polls;
pub mod rate_limit;
pub mod routes;
pub mod saved_searches;
pub mod scim;
pub mod sso;
pub mod state;
pub mod stream_mod;
pub mod user_status;
pub mod vod;
pub mod webhooks;
pub mod workspaces;
pub mod ws;
pub mod channels;
pub mod commands;
pub mod forward;
pub mod message_reminders;
pub mod scheduled;
pub mod scheduled_streams;
pub mod search;
pub mod translate;
// Wave 10 (0033-0038).
pub mod announcements;
pub mod favorites;
pub mod keyword_alerts;
pub mod message_history;
pub mod profiles;
pub mod user_groups;
// Wave 11.
pub mod files;
pub mod read_all;
pub mod stream_follows;
pub mod thread_subs;
// Wave 12.
pub mod dm;
pub mod recurring;
pub mod catchup;
pub mod reaction_detail;
pub mod default_channels;
// Wave 13.
pub mod group_dm;
pub mod action_items;
pub mod join_requests;
pub mod conversation_export;

pub use state::AppState;
