//! Personal Access Token (PAT) repository — programmatic REST API auth.
//!
//! Backs `migrations/0019_pat.sql`. A participant mints a long-lived token
//! (`aero_pat_<random>`) and presents it in the `Authorization: Bearer` header
//! in place of a short-lived access JWT. Every `AuthUser`-gated route becomes
//! callable with a PAT (see the `aero-auth` extractor wiring).
//!
//! Purely additive: a NEW [`PatRepo`]; no existing repo is touched.
//!
//! ## Security model (mirrors password / SCIM / webhook token handling)
//!
//! Only the SHA-256 *hash* of a token is stored. The plaintext is generated by
//! [`generate_pat`], returned to the caller exactly once at mint time, and never
//! persisted. On every request the incoming token is hashed with [`hash_pat`]
//! and resolved with [`PatRepo::verify`] — a single indexed point lookup that
//! returns the owner IFF the token is active (not revoked, not expired). A leaked
//! `pat_tokens` table therefore yields no usable credentials.
//!
//! The hashing/generation helpers are pure free functions so they unit-test
//! offline, keeping testable logic separate from live SQL (Postgres is absent in
//! CI). They are named `generate_pat` / `hash_pat` (rather than the
//! `generate_token` / `hash_token` other token modules use on live master) so
//! they can be re-exported at the crate root without a name clash.

use aero_common::{ParticipantId, PatId};
use serde::Serialize;
use sha2::{Digest, Sha256};
use sqlx::PgPool;

/// One PAT as shown in a management listing — metadata only. Never carries the
/// plaintext or the hash, so listing a participant's tokens can never leak a
/// usable credential.
#[derive(Debug, Clone, Serialize)]
pub struct PatSummary {
    pub id: PatId,
    pub name: Option<String>,
    pub scopes: Vec<String>,
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: time::OffsetDateTime,
    #[serde(with = "time::serde::rfc3339::option")]
    pub last_used_at: Option<time::OffsetDateTime>,
    #[serde(with = "time::serde::rfc3339::option")]
    pub expires_at: Option<time::OffsetDateTime>,
    #[serde(with = "time::serde::rfc3339::option")]
    pub revoked_at: Option<time::OffsetDateTime>,
}

/// The opaque prefix every minted PAT carries, so it is recognizable in logs /
/// config and so the [`AuthUser`](../../aero_auth/extractor/struct.AuthUser.html)
/// extractor can cheaply tell a PAT apart from a JWT before hashing.
pub const PAT_PREFIX: &str = "aero_pat_";

/// Generate a high-entropy personal access token: the [`PAT_PREFIX`] followed by
/// 256 bits of randomness (hex-encoded). The plaintext is returned to the caller
/// exactly once at mint time; only its [`hash_pat`] is persisted. Lives here
/// (next to the hash) so the server crate needs no `rand` dependency.
#[must_use]
pub fn generate_pat() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 32]; // 256 bits of entropy
    rand::rngs::OsRng.fill_bytes(&mut bytes);
    let mut s = String::with_capacity(PAT_PREFIX.len() + bytes.len() * 2);
    s.push_str(PAT_PREFIX);
    for byte in bytes {
        use std::fmt::Write as _;
        let _ = write!(s, "{byte:02x}");
    }
    s
}

/// Hash a PAT for storage / lookup.
///
/// SHA-256 hex. A PAT is a long random secret (not a low-entropy password), so a
/// fast cryptographic digest is the right primitive: it makes the stored value
/// useless if the table leaks, while keeping the per-request resolve a single
/// indexed lookup. Pure, so it is unit-tested without a DB.
#[must_use]
pub fn hash_pat(token: &str) -> String {
    let digest = Sha256::digest(token.as_bytes());
    let mut s = String::with_capacity(digest.len() * 2);
    for byte in digest {
        use std::fmt::Write as _;
        let _ = write!(s, "{byte:02x}");
    }
    s
}

/// Cheap-to-clone (clones share the underlying `PgPool`).
#[derive(Clone)]
pub struct PatRepo {
    pool: PgPool,
}

impl PatRepo {
    #[must_use]
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Mint a PAT for a participant, storing only its hash. `token_hash` must
    /// already be [`hash_pat`]ed by the caller (the route hashes the freshly
    /// generated plaintext and returns the plaintext exactly once). `expires_at`
    /// of `None` means the token never expires. Returns the new token's id.
    ///
    /// Security-event audit: the mint commits with an `auth.pat.issue` row in
    /// the SAME transaction (same-fate — a failed audit insert rolls the token
    /// back; a committed token always has its audit row). Account-level event:
    /// workspace = the nil default tenant. The B5-1 route orchestrates the
    /// governance PAIR on top of [`create_in_tx`](Self::create_in_tx); this
    /// pool method keeps the legacy audit-only append so the existing `db_tests`
    /// pass verbatim.
    pub async fn create(
        &self,
        participant: ParticipantId,
        token_hash: &str,
        name: Option<&str>,
        scopes: &[String],
        expires_at: Option<time::OffsetDateTime>,
    ) -> Result<PatId, sqlx::Error> {
        let mut tx = self.pool.begin().await?;
        let id = Self::create_in_tx(&mut tx, participant, token_hash, name, scopes, expires_at)
            .await?;
        crate::AuditRepo::append_in_tx(
            &mut tx,
            aero_common::WorkspaceId::nil(),
            Some(participant),
            crate::audit_governance::tokens::AUTH_PAT_ISSUE,
            Some(&id.to_string()),
            serde_json::json!({
                "name": name,
                "scopes": scopes,
                "expires_at": expires_at,
            }),
        )
        .await?;
        tx.commit().await?;
        Ok(id)
    }

    /// Transaction-scoped mint (B5-1 route path): the INSERT only — no audit,
    /// no begin/commit. The route appends the governance pair via
    /// [`AuditGovernanceOutboxRepo::append_pair_in_tx_fail_open`] before
    /// committing.
    ///
    /// # Errors
    /// Propagates any [`sqlx::Error`].
    pub async fn create_in_tx(
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        participant: ParticipantId,
        token_hash: &str,
        name: Option<&str>,
        scopes: &[String],
        expires_at: Option<time::OffsetDateTime>,
    ) -> Result<PatId, sqlx::Error> {
        let id = PatId::new();
        sqlx::query(
            r"INSERT INTO pat_tokens (id, participant_id, token_hash, name, scopes, expires_at, created_at)
               VALUES ($1, $2, $3, $4, $5, $6, now())",
        )
        .bind(id.to_uuid())
        .bind(participant.to_uuid())
        .bind(token_hash)
        .bind(name)
        .bind(scopes)
        .bind(expires_at)
        .execute(&mut **tx)
        .await?;
        Ok(id)
    }

    /// Resolve an incoming token hash to its owner — the PAT authentication check.
    ///
    /// Returns the owning [`ParticipantId`] IFF the token is **active**: it exists,
    /// is not revoked (`revoked_at IS NULL`), and is not expired
    /// (`expires_at IS NULL OR expires_at > now()`). Returns `None` otherwise.
    ///
    /// On a hit it best-effort bumps `last_used_at = now()` (a separate statement
    /// whose failure is swallowed) so a stale clock or transient write error can
    /// never turn a valid token into a 401.
    pub async fn verify(&self, token_hash: &str) -> Result<Option<ParticipantId>, sqlx::Error> {
        let row = sqlx::query_as::<_, (uuid::Uuid,)>(
            r"SELECT participant_id FROM pat_tokens
               WHERE token_hash = $1
                 AND revoked_at IS NULL
                 AND (expires_at IS NULL OR expires_at > now())
                 -- Defence-in-depth: a PAT must not authenticate a deleted /
                 -- GDPR-erased participant. Erasure also deletes the token row
                 -- (participant.rs), but the tombstone is authoritative here so a
                 -- surviving/raced token still can't grant access.
                 AND EXISTS (
                     SELECT 1 FROM participants p
                      WHERE p.id = pat_tokens.participant_id
                        AND p.deleted_at IS NULL)",
        )
        .bind(token_hash)
        .fetch_optional(&self.pool)
        .await?;

        let Some((participant,)) = row else {
            return Ok(None);
        };

        // Best-effort "last seen" bump — never let it fail the auth check.
        let _ = sqlx::query(r"UPDATE pat_tokens SET last_used_at = now() WHERE token_hash = $1")
            .bind(token_hash)
            .execute(&self.pool)
            .await;

        Ok(Some(ParticipantId::from_uuid(participant)))
    }

    /// List a participant's tokens, newest first. Returns metadata only — never
    /// the hash or plaintext — so a listing can never surface a usable credential.
    /// Revoked tokens are included (with their `revoked_at` set) so a UI can show
    /// history; the caller can filter if it wants only active ones.
    pub async fn list(&self, participant: ParticipantId) -> Result<Vec<PatSummary>, sqlx::Error> {
        let rows = sqlx::query_as::<_, PatSqlRow>(
            r"SELECT id, name, scopes, created_at, last_used_at, expires_at, revoked_at
               FROM pat_tokens
               WHERE participant_id = $1
               ORDER BY created_at DESC, id DESC",
        )
        .bind(participant.to_uuid())
        .fetch_all(&self.pool)
        .await?;
        Ok(rows.into_iter().map(PatSummary::from).collect())
    }

    /// Revoke a token the caller owns (idempotent — a no-op if already revoked,
    /// absent, or owned by someone else). Owner-scoped: the `participant_id`
    /// predicate means one participant can never revoke another's token. Returns
    /// `true` if a still-active row that the caller owns was revoked by this call.
    ///
    /// Security-event audit: a successful (rows-affected) revoke commits an
    /// `auth.pat.revoke` row in the SAME transaction (same-fate); a no-op
    /// revoke (non-owned / already revoked) commits nothing and audits nothing.
    /// The B5-1 route orchestrates the governance PAIR on top of
    /// [`revoke_in_tx`](Self::revoke_in_tx); this pool method keeps the legacy
    /// audit-only append so the existing `db_tests` pass verbatim.
    pub async fn revoke(&self, id: PatId, participant: ParticipantId) -> Result<bool, sqlx::Error> {
        let mut tx = self.pool.begin().await?;
        let revoked = Self::revoke_in_tx(&mut tx, id, participant).await?;
        if revoked {
            crate::AuditRepo::append_in_tx(
                &mut tx,
                aero_common::WorkspaceId::nil(),
                Some(participant),
                crate::audit_governance::tokens::AUTH_PAT_REVOKE,
                Some(&id.to_string()),
                serde_json::json!({ "id": id.to_string() }),
            )
            .await?;
        }
        tx.commit().await?;
        Ok(revoked)
    }

    /// Transaction-scoped revoke (B5-1 route path): the UPDATE only — no audit,
    /// no begin/commit. Idempotency unchanged (`revoked_at IS NULL` predicate,
    /// rows-affected semantics): a no-op revoke audits nothing (the route
    /// appends the pair only when this returns `true`).
    ///
    /// # Errors
    /// Propagates any [`sqlx::Error`].
    pub async fn revoke_in_tx(
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        id: PatId,
        participant: ParticipantId,
    ) -> Result<bool, sqlx::Error> {
        let result = sqlx::query(
            r"UPDATE pat_tokens SET revoked_at = now()
               WHERE id = $1 AND participant_id = $2 AND revoked_at IS NULL",
        )
        .bind(id.to_uuid())
        .bind(participant.to_uuid())
        .execute(&mut **tx)
        .await?;
        Ok(result.rows_affected() > 0)
    }
}

/// sqlx row shape for `pat_tokens` listing decode (metadata only — no hash).
#[derive(sqlx::FromRow)]
struct PatSqlRow {
    id: uuid::Uuid,
    name: Option<String>,
    scopes: Vec<String>,
    created_at: time::OffsetDateTime,
    last_used_at: Option<time::OffsetDateTime>,
    expires_at: Option<time::OffsetDateTime>,
    revoked_at: Option<time::OffsetDateTime>,
}

impl From<PatSqlRow> for PatSummary {
    fn from(r: PatSqlRow) -> Self {
        Self {
            id: PatId::from_uuid(r.id),
            name: r.name,
            scopes: r.scopes,
            created_at: r.created_at,
            last_used_at: r.last_used_at,
            expires_at: r.expires_at,
            revoked_at: r.revoked_at,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hash_pat_is_stable_hex_sha256() {
        // Known SHA-256 of the empty string and "abc" (FIPS 180-4 examples).
        assert_eq!(
            hash_pat(""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            hash_pat("abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        // Hex, 64 chars, deterministic and input-sensitive.
        let h = hash_pat("a-pat-secret");
        assert_eq!(h.len(), 64);
        assert!(h.bytes().all(|b| b.is_ascii_hexdigit()));
        assert_eq!(h, hash_pat("a-pat-secret"));
        assert_ne!(h, hash_pat("a-pat-secre"));
    }

    #[test]
    fn generate_pat_is_prefixed_high_entropy_and_hashable() {
        let a = generate_pat();
        let b = generate_pat();
        assert!(a.starts_with(PAT_PREFIX));
        // prefix + 32 bytes * 2 hex chars = 256-bit secret.
        assert_eq!(a.len(), PAT_PREFIX.len() + 64, "256-bit hex secret");
        assert_ne!(a, b, "two mints differ");
        // The generated secret hashes to a stable 64-char hex digest.
        assert_eq!(hash_pat(&a).len(), 64);
    }
}

/// PG-gated integration tests (run with a live Postgres + applied migrations):
///
/// ```text
/// DATABASE_URL=postgres://aero:aero_dev_pw@localhost:5432/aero \
///   cargo test -p aero-storage --lib -- --ignored pat_
/// ```
///
/// They are `#[ignore]` so the default `cargo test` stays hermetic (no DB in CI).
#[cfg(test)]
mod db_tests {
    use super::*;
    use aero_common::ParticipantId;

    fn pool() -> PgPool {
        let url = std::env::var("DATABASE_URL")
            .unwrap_or_else(|_| "postgres://aero:aero_dev_pw@localhost:5432/aero".into());
        sqlx::postgres::PgPoolOptions::new()
            .max_connections(2)
            .connect_lazy(&url)
            .expect("connect_lazy never fails on a well-formed URL")
    }

    async fn new_participant(p: &PgPool) -> ParticipantId {
        let id = ParticipantId::new();
        sqlx::query("INSERT INTO participants (id, kind, display_name) VALUES ($1, 'human', $2)")
            .bind(id.to_uuid())
            .bind(format!("pat-user-{id}"))
            .execute(p)
            .await
            .expect("insert participant");
        id
    }

    #[tokio::test]
    #[ignore = "requires live Postgres"]
    async fn pat_create_verify_revoke_cycle() {
        let p = pool();
        let repo = PatRepo::new(p.clone());
        let owner = new_participant(&p).await;

        let secret = generate_pat();
        let scopes = vec!["read".to_owned(), "write".to_owned()];
        let id = repo
            .create(owner, &hash_pat(&secret), Some("ci"), &scopes, None)
            .await
            .unwrap();

        // An active token resolves to its owner …
        assert_eq!(repo.verify(&hash_pat(&secret)).await.unwrap(), Some(owner));
        // … and an unknown hash does not.
        assert_eq!(repo.verify("deadbeef").await.unwrap(), None);

        // It shows up in the owner's listing, metadata only (scopes round-trip).
        let listed = repo.list(owner).await.unwrap();
        assert!(listed.iter().any(|t| t.id == id && t.scopes == scopes));

        // A different participant cannot revoke it (owner-scoped) …
        let other = new_participant(&p).await;
        assert!(!repo.revoke(id, other).await.unwrap(), "not owner ⇒ no-op");
        assert_eq!(
            repo.verify(&hash_pat(&secret)).await.unwrap(),
            Some(owner),
            "still active after a non-owner revoke attempt"
        );

        // … but the owner can, after which it no longer verifies, and a second
        // revoke is a no-op.
        assert!(
            repo.revoke(id, owner).await.unwrap(),
            "owner revoke succeeds"
        );
        assert_eq!(repo.verify(&hash_pat(&secret)).await.unwrap(), None);
        assert!(
            !repo.revoke(id, owner).await.unwrap(),
            "second revoke is a no-op"
        );

        // Security-event audit (AC1b): the mint committed exactly one
        // `auth.pat.issue` row (nil workspace, actor = owner, target = the
        // token id, detail per R1); the owner revoke committed exactly one
        // `auth.pat.revoke` row; the non-owner attempt and the second (no-op)
        // revoke added ZERO rows — counts scoped by actor_id (the sibling
        // `pat_expired_token_does_not_verify` test mints its own tokens).
        let create: (String, String, String, Option<String>, serde_json::Value) =
            sqlx::query_as(
                "SELECT workspace_id::text, actor_id::text, target, detail->>'expires_at', detail
                   FROM audit_events
                  WHERE action = 'auth.pat.issue' AND actor_id = $1",
            )
            .bind(owner.to_uuid())
            .fetch_one(&p)
            .await
            .expect("exactly one auth.pat.issue row");
        assert_eq!(create.0, "00000000-0000-0000-0000-000000000000", "nil workspace");
        assert_eq!(create.1, owner.to_uuid().to_string(), "actor = owner");
        assert_eq!(create.2, id.to_string(), "target = the PAT id");
        assert_eq!(create.4["name"], "ci");
        assert_eq!(create.4["scopes"], serde_json::json!(["read", "write"]));
        assert!(create.3.is_none(), "expires_at null when absent");
        let create_total: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM audit_events WHERE action = 'auth.pat.issue' AND actor_id = $1",
        )
        .bind(owner.to_uuid())
        .fetch_one(&p)
        .await
        .unwrap();
        assert_eq!(create_total, 1, "one create row per mint");
        let create_other: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM audit_events WHERE action = 'auth.pat.issue' AND actor_id = $1",
        )
        .bind(other.to_uuid())
        .fetch_one(&p)
        .await
        .unwrap();
        assert_eq!(create_other, 0, "the non-owner minted nothing");

        let revoke: (String, String, String) = sqlx::query_as(
            "SELECT workspace_id::text, actor_id::text, detail->>'id'
               FROM audit_events
              WHERE action = 'auth.pat.revoke' AND actor_id = $1",
        )
        .bind(owner.to_uuid())
        .fetch_one(&p)
        .await
        .expect("exactly one auth.pat.revoke row");
        assert_eq!(revoke.0, "00000000-0000-0000-0000-000000000000", "nil workspace");
        assert_eq!(revoke.1, owner.to_uuid().to_string(), "actor = owner");
        assert_eq!(revoke.2, id.to_string(), "detail.id = the revoked token id");
        let revoke_total: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM audit_events WHERE action = 'auth.pat.revoke' AND actor_id = $1",
        )
        .bind(owner.to_uuid())
        .fetch_one(&p)
        .await
        .unwrap();
        assert_eq!(
            revoke_total, 1,
            "non-owner attempt and second revoke are no-ops: revoke count stays 1"
        );
    }

    #[tokio::test]
    #[ignore = "requires live Postgres"]
    async fn pat_expired_token_does_not_verify() {
        let p = pool();
        let repo = PatRepo::new(p.clone());
        let owner = new_participant(&p).await;

        let secret = generate_pat();
        // Already expired one hour ago.
        let past = time::OffsetDateTime::now_utc() - time::Duration::hours(1);
        repo.create(owner, &hash_pat(&secret), None, &[], Some(past))
            .await
            .unwrap();

        assert_eq!(
            repo.verify(&hash_pat(&secret)).await.unwrap(),
            None,
            "an expired token never authenticates"
        );

        // A token expiring in the future still verifies.
        let secret2 = generate_pat();
        let future = time::OffsetDateTime::now_utc() + time::Duration::hours(1);
        repo.create(owner, &hash_pat(&secret2), None, &[], Some(future))
            .await
            .unwrap();
        assert_eq!(repo.verify(&hash_pat(&secret2)).await.unwrap(), Some(owner));
    }
}
