use std::sync::Arc;

use aero_common::{CallId, ParticipantId, SfuSubscription};
use parking_lot::Mutex;

use super::SfuForwarder;
use crate::{BridgeRtp, InboundRtp, KeyframeRequestKind, Mid, SfuPeerSink, SfuRouter};

#[derive(Default)]
struct RecordingSink {
    rtp: Mutex<Vec<InboundRtp>>,
    keyframes: Mutex<Vec<(String, KeyframeRequestKind)>>,
    rembs: Mutex<Vec<(String, u64)>>,
}

impl SfuPeerSink for RecordingSink {
    fn try_write_rtp(&self, packet: InboundRtp) -> bool {
        self.rtp.lock().push(packet);
        true
    }

    fn try_request_keyframe(&self, mid: Mid, kind: KeyframeRequestKind) -> bool {
        self.keyframes.lock().push((mid.to_string(), kind));
        true
    }

    fn try_request_remb(&self, mid: Mid, bitrate_bps: u64) -> bool {
        self.rembs.lock().push((mid.to_string(), bitrate_bps));
        true
    }
}

fn route(publisher: ParticipantId, pub_mid: &str, out_mid: &str) -> SfuSubscription {
    SfuSubscription {
        publisher,
        pub_mid: pub_mid.into(),
        out_mid: out_mid.into(),
    }
}

#[test]
fn three_participants_with_identical_publish_mids_use_distinct_outbound_slots() {
    let call = CallId::new();
    let publisher_a = ParticipantId::new();
    let publisher_b = ParticipantId::new();
    let subscriber = ParticipantId::new();
    let forwarder = SfuForwarder::new(SfuRouter::new());
    let sink_a = Arc::new(RecordingSink::default());
    let sink_b = Arc::new(RecordingSink::default());
    let sink_sub = Arc::new(RecordingSink::default());
    forwarder.attach_peer_sink(call, publisher_a, sink_a);
    forwarder.attach_peer_sink(call, publisher_b, sink_b);
    forwarder.attach_peer_sink(call, subscriber, sink_sub.clone());

    assert_eq!(
        forwarder.replace_call_subscriptions(
            call,
            subscriber,
            &[
                route(publisher_a, "0", "recv-a"),
                route(publisher_b, "0", "recv-b"),
            ],
        ),
        2,
        "installing each source queues an initial PLI"
    );

    let packet_a = BridgeRtp::new(publisher_a, "0", vec![0xAA], true).to_inbound();
    let packet_b = BridgeRtp::new(publisher_b, "0", vec![0xBB], true).to_inbound();
    assert_eq!(forwarder.on_call_rtp(call, publisher_a, &packet_a), 1);
    assert_eq!(forwarder.on_call_rtp(call, publisher_b, &packet_b), 1);

    let received = sink_sub.rtp.lock();
    assert_eq!(received.len(), 2);
    assert_eq!(received[0].mid.to_string(), "recv_a");
    assert_eq!(received[0].payload, vec![0xAA]);
    assert_eq!(received[1].mid.to_string(), "recv_b");
    assert_eq!(received[1].payload, vec![0xBB]);
}

#[test]
fn subscriber_feedback_reaches_only_the_mapped_publisher_owner() {
    let call = CallId::new();
    let publisher_a = ParticipantId::new();
    let publisher_b = ParticipantId::new();
    let subscriber = ParticipantId::new();
    let forwarder = SfuForwarder::new(SfuRouter::new());
    let sink_a = Arc::new(RecordingSink::default());
    let sink_b = Arc::new(RecordingSink::default());
    forwarder.attach_peer_sink(call, publisher_a, sink_a.clone());
    forwarder.attach_peer_sink(call, publisher_b, sink_b.clone());
    forwarder.attach_peer_sink(call, subscriber, Arc::new(RecordingSink::default()));
    forwarder.replace_call_subscriptions(
        call,
        subscriber,
        &[
            route(publisher_a, "0", "recv-a"),
            route(publisher_b, "0", "recv-b"),
        ],
    );
    // Ignore the initial subscription PLIs; exercise feedback generated by
    // str0m on the subscriber leg.
    sink_a.keyframes.lock().clear();
    sink_b.keyframes.lock().clear();

    assert!(forwarder.on_call_keyframe_request(
        call,
        subscriber,
        "recv-b",
        KeyframeRequestKind::Fir,
    ));
    assert!(sink_a.keyframes.lock().is_empty());
    assert_eq!(
        sink_b.keyframes.lock().as_slice(),
        &[("0".into(), KeyframeRequestKind::Fir)]
    );

    assert_eq!(
        forwarder.on_call_bandwidth_estimate(call, subscriber, Some("recv-b"), 640_000,),
        1
    );
    assert!(sink_a.rembs.lock().is_empty());
    assert_eq!(sink_b.rembs.lock().as_slice(), &[("0".into(), 640_000)]);
}

#[test]
fn publisher_feedback_falls_back_across_local_and_bridge_owner_handoffs() {
    let call = CallId::new();
    let publisher = ParticipantId::new();
    let subscriber = ParticipantId::new();
    let forwarder = SfuForwarder::new(SfuRouter::new());
    let bridge_a = Arc::new(RecordingSink::default());
    let bridge_b = Arc::new(RecordingSink::default());
    let local = Arc::new(RecordingSink::default());

    forwarder.attach_bridge_peer_sink(call, publisher, "node-a", bridge_a.clone());
    forwarder.attach_bridge_peer_sink(call, publisher, "node-b", bridge_b.clone());
    forwarder.attach_peer_sink(call, publisher, local.clone());
    forwarder.attach_peer_sink(call, subscriber, Arc::new(RecordingSink::default()));
    forwarder.replace_call_subscriptions(call, subscriber, &[route(publisher, "0", "recv")]);
    bridge_a.keyframes.lock().clear();
    bridge_b.keyframes.lock().clear();
    local.keyframes.lock().clear();

    assert!(forwarder.on_call_keyframe_request(call, subscriber, "recv", KeyframeRequestKind::Pli,));
    assert_eq!(local.keyframes.lock().len(), 1);
    assert!(bridge_a.keyframes.lock().is_empty());
    assert!(bridge_b.keyframes.lock().is_empty());

    assert!(forwarder.detach_peer_sink(call, publisher));
    assert_eq!(
        bridge_b.keyframes.lock().as_slice(),
        &[("0".into(), KeyframeRequestKind::Pli)],
        "ownership fallback immediately asks the newest bridge for a fresh frame"
    );
    bridge_b.keyframes.lock().clear();
    assert!(forwarder.on_call_keyframe_request(call, subscriber, "recv", KeyframeRequestKind::Fir,));
    assert_eq!(
        bridge_b.keyframes.lock().as_slice(),
        &[("0".into(), KeyframeRequestKind::Fir)],
        "the newest live bridge takes over after local ownership leaves"
    );

    assert!(forwarder.detach_bridge_peer_sink(call, publisher, "node-b"));
    assert_eq!(
        bridge_a.keyframes.lock().as_slice(),
        &[("0".into(), KeyframeRequestKind::Pli)],
        "bridge-to-bridge handoff immediately refreshes the fallback source"
    );
    bridge_a.keyframes.lock().clear();
    assert!(forwarder.on_call_keyframe_request(call, subscriber, "recv", KeyframeRequestKind::Pli,));
    assert_eq!(
        bridge_a.keyframes.lock().as_slice(),
        &[("0".into(), KeyframeRequestKind::Pli)],
        "the older bridge remains usable after its successor detaches"
    );
}

#[test]
fn reconnect_clears_new_generation_subscriptions_but_preserves_publisher_routes() {
    let call = CallId::new();
    let reconnecting = ParticipantId::new();
    let other_publisher = ParticipantId::new();
    let other_subscriber = ParticipantId::new();
    let forwarder = SfuForwarder::new(SfuRouter::new());
    forwarder.attach_peer_sink(call, reconnecting, Arc::new(RecordingSink::default()));
    forwarder.attach_peer_sink(call, other_publisher, Arc::new(RecordingSink::default()));
    let subscriber_sink = Arc::new(RecordingSink::default());
    forwarder.attach_peer_sink(call, other_subscriber, subscriber_sink.clone());
    forwarder.replace_call_subscriptions(
        call,
        reconnecting,
        &[route(other_publisher, "0", "recv-other")],
    );
    forwarder.replace_call_subscriptions(
        call,
        other_subscriber,
        &[route(reconnecting, "0", "recv-reconnected")],
    );

    assert!(forwarder.reset_peer_sink(call, reconnecting));
    forwarder.attach_peer_sink(call, reconnecting, Arc::new(RecordingSink::default()));

    let from_other = BridgeRtp::new(other_publisher, "0", vec![0xAA], true).to_inbound();
    assert_eq!(
        forwarder.on_call_rtp(call, other_publisher, &from_other),
        0,
        "a new session generation must explicitly resubscribe"
    );
    let from_reconnected = BridgeRtp::new(reconnecting, "0", vec![0xBB], true).to_inbound();
    assert_eq!(
        forwarder.on_call_rtp(call, reconnecting, &from_reconnected),
        1,
        "other participants keep their routes to unchanged publisher tracks"
    );
    assert_eq!(subscriber_sink.rtp.lock()[0].payload, vec![0xBB]);
}

#[test]
fn replacing_and_detaching_routes_withdraws_subscriber_remb_state() {
    let call = CallId::new();
    let publisher = ParticipantId::new();
    let slow = ParticipantId::new();
    let fast = ParticipantId::new();
    let forwarder = SfuForwarder::new(SfuRouter::new());
    let publisher_sink = Arc::new(RecordingSink::default());
    forwarder.attach_peer_sink(call, publisher, publisher_sink.clone());
    forwarder.attach_peer_sink(call, slow, Arc::new(RecordingSink::default()));
    forwarder.attach_peer_sink(call, fast, Arc::new(RecordingSink::default()));
    forwarder.replace_call_subscriptions(call, slow, &[route(publisher, "0", "recv")]);
    forwarder.replace_call_subscriptions(call, fast, &[route(publisher, "0", "recv")]);

    assert_eq!(
        forwarder.on_call_bandwidth_estimate(call, slow, Some("recv"), 200_000),
        1
    );
    let _ = forwarder.on_call_bandwidth_estimate(call, fast, Some("recv"), 1_000_000);
    publisher_sink.rembs.lock().clear();

    forwarder.replace_call_subscriptions(call, slow, &[]);
    let source = super::CallTrack::new(publisher, "0");
    assert_eq!(
        forwarder.inner.lock().call_remb_agg[&(call, source)].subscriber_count(),
        1,
        "unsubscribed peers must no longer constrain publisher bandwidth"
    );
    assert!(
        !publisher_sink.rembs.lock().is_empty(),
        "dropping the slowest route immediately lifts publisher REMB"
    );

    assert!(forwarder.detach_peer_sink(call, fast));
    assert!(
        forwarder.inner.lock().call_remb_agg.is_empty(),
        "last-subscriber cleanup removes empty aggregators"
    );
}
