server {
    listen 127.0.0.1:18080;
    location / {
        resolver 127.0.0.11 ipv6=off valid=10s;
        set $snaplink snaplink:8080;
        proxy_pass http://$snaplink;
        proxy_set_header Host $host;
        proxy_set_header X-Request-ID $request_id;
    }
}
